#ifndef _ANYWHERE_MODE_H_
#define _ANYWHERE_MODE_H_

#include <stdlib.h>
#include <string.h>
#include <glib.h>

enum MP4_SEPARATE
{
    MP4_SEPARATE_10,
    MP4_SEPARATE_20,
    MP4_SEPARATE_30,
    MP4_SEPARATE_60,
    MP4_SEPARATE_NONE
};

enum LIVE_RESOLUTION
{
    LIVE_RESOLUTION_4K,
    LIVE_RESOLUTION_6K,
    LIVE_RESOLUTION_8K
};

enum LIVE_BITRATE
{
    LIVE_BITRATE_5M,
    LIVE_BITRATE_10M,
    LIVE_BITRATE_15M,
    LIVE_BITRATE_30M,
    LIVE_BITRATE_40M,
    LIVE_BITRATE_50M,
    LIVE_BITRATE_60M
};

enum WIFI_MODE
{
    WIFI_MODE_AP,
    WIFI_MODE_STATION,
    WIFI_MODE_OFF
};

enum LED_MODE
{
    LED_MODE_ON,
    LED_MODE_OFF
};

enum LAN_MODE
{
    LAN_MODE_DHCP,
    LAN_MODE_MANUAL
};

enum WORKMODE
{
    WORKMODE_JPEG,
    WORKMODE_MP4,
    WORKMODE_LIVE,
    WORKMODE_SETTING
};

enum NETWORK_STATE
{
    NETWORK_WIRE,
    NETWORK_WIFI
};

enum BATTERY_STATE
{
    BATTERY_LESS_THAN_5 = 0,
    BATTERY_10,
    BATTERY_20,
    BATTERY_40,
    BATTERY_50,
    BATTERY_80,
    BATTERY_100,
    BATTERY_POWER
};
enum EXPO_MODE
{
    EXPO_MODE_AUTO,
    EXPO_MODE_MANUAL,
    EXPO_MODE_SHUTTER,
    EXPO_MODE_ISO
};

enum EXPO_ISO_MODE
{
    EXPO_ISO_AUTO,
    EXPO_ISO_LT_100,
    EXPO_ISO_100,
    EXPO_ISO_LT_200,
    EXPO_ISO_200,
    EXPO_ISO_LT_400,
    EXPO_ISO_400,
    EXPO_ISO_LT800,
    EXPO_ISO_800,
    EXPO_ISO_LT1600,
    EXPO_ISO_1600
};

enum EXPO_SHUTTER_MODE
{
    EXPO_SHUTTER_AUTO,
    EXPO_SHUTTER_D3200,
    EXPO_SHUTTER_GTD3200,
    EXPO_SHUTTER_D1000,
    EXPO_SHUTTER_GTD1000,
    EXPO_SHUTTER_D500,
    EXPO_SHUTTER_GTD500,
    EXPO_SHUTTER_D100,
    EXPO_SHUTTER_GTD100,
    EXPO_SHUTTER_D50,
    EXPO_SHUTTER_GTD50,
    EXPO_SHUTTER_D30,
    EXPO_SHUTTER_GTD30,
    EXPO_SHUTTER_D15,
    EXPO_SHUTTER_GTD15
};

enum IS_SELECTED
{
    SELECT_NO,
    SELECT_YES
}

#endif